FROM node:18 as builder

# Create app directory
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copy code and build
COPY . .
RUN npm run build   # <-- loads .env.production

# Production stage
FROM node:18-slim
WORKDIR /usr/src/app

# Install "serve" to serve static files
RUN npm install -g serve

# Copy build output from builder
COPY --from=builder /usr/src/app/build ./build

EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]